project:
  type: book
  output-dir: docs

book:
  title: "Meget mere mat"
  author: "Selma og Lasse"
  date: "today"
  language: "da"
  chapters:
    - index.qmd
    - parabler.qmd
    - enheder.qmd
    - potenser-rodder.qmd
    - logaritmer.qmd
    - differentialregning.qmd
    - kombinatorik.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    toc-title: "Indhold"

crossref:
  chapters: true

execute:
  echo: false
  warning: false
  message: false
  freeze: auto

lang: "da"